### ISSUE TITLE
fails on properties

### ISSUE THREAD

**Issue by davidkarlsen** [stakater/Forecastle#90] opened 2020-01-03 19:41 UTC
annotated the ingress with:
      `forecastle.stakater.com/properties: "finodsGroup=test1,applicationEnvironment=test2"`

and it fails with:
```
time="2020-01-03T19:40:10Z" level=info msg="Found ingress with Name 'eos-jfr-srv-d1-fsjetty' in Namespace 'eos-jfr-srv-d1'" _source="filename/filename.go:22"
github.com/stakater/Forecastle/pkg/forecastle/ingressapps.convertIngressesToForecastleApps(0xc000680000, 0x8, 0x8, 0x1, 0xc0000171c8, 0xc0000ac060)
        /go/src/github.com/stakater/Forecastle/pkg/forecastle/ingressapps/apps.go:74 +0x413
github.com/stakater/Forecastle/pkg/forecastle/ingressapps.(*List).Populate(0xc0000178d8, 0xc0004952e0, 0x1, 0x1, 0x2)
        /go/src/github.com/stakater/Forecastle/pkg/forecastle/ingressapps/apps.go:52 +0x209
github.com/stakater/Forecastle/pkg/handlers.AppsHandler(0x1776d40, 0xc0003c0000, 0xc00053c800)
        /go/src/github.com/stakater/Forecastle/pkg/handlers/appsHandler.go:44 +0x521
net/http.HandlerFunc.ServeHTTP(0x162b318, 0x1776d40, 0xc0003c0000, 0xc00053c800)
        /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000270b60, 0x1776d40, 0xc0003c0000, 0xc00053c800)
        /go/pkg/mod/github.com/gorilla/mux@v1.6.2/mux.go:162 +0x104
net/http.serverHandler.ServeHTTP(0xc0001461c0, 0x1776d40, 0xc0003c0000, 0xc00053c400)
        /usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0000a2aa0, 0x177aac0, 0xc0004ef540)
        /usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2927 +0x38e```

**Comment by davidkarlsen** [comment] 2020-01-16 11:38
@waseem-h any idea?

**Comment by waseem-h** [comment] 2020-01-16 11:39
It looks like a potential bug. I will see if I can reproduce it on my environment and if I can, I'll try to release a fix. Will keep you posted here @davidkarlsen

**Comment by waseem-h** [comment] 2020-01-17 06:56
@davidkarlsen can you specify the properties as `finodsGroup:test1,applicationEnvironment:test2`? I checked the code and the separator between keys and values is actually `:` and not `=` and thats why you're seeing this issue. Let me know if this works for you and feel free to re-open this if it is not fixed by the above.

**Closed by waseem-h** 2020-01-17 06:56 UTC
Labels: kind/bug

**Comment by davidkarlsen** [comment] 2020-01-17 09:32
That works - I added a PR for slightly updating docs.
